import Head from "next/head";
import styles from "../styles/Obsoverlay.module.css";
import {useEffect, useState} from "react";
import axios from "axios";

export default function Home() {
  const [spotifyAuthorized, setSpotifyAuthorized] = useState(false)
  const [spotifyCurrentSong, setSpotifyCurrentSong] = useState(null)

  const fetchSpotifySong = async () => {
    try {
      const {data} = await axios.get('/api/spotify-current-song')
      setSpotifyAuthorized(true)
      if (data.current) {
        setSpotifyCurrentSong(data.current)
      } else {
        setSpotifyCurrentSong(null)
      }
    } catch (e) {
      setSpotifyAuthorized(false)
    }
  }
  useEffect(() => {
    fetchSpotifySong()
  }, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>

      <div className={styles.container}>
        <div className={styles.title}>
          Последний подписчик: <span id="lastFollower">---</span>
        </div>
        <div className={styles.title}>
          Последний донат: <span id="lastDonation">---</span>
        </div>
        <div className={styles.title}>
          Сейчас играет:{" "}
          {spotifyAuthorized ? <>
            <span id="currentTrack">
              {" "}
              {spotifyCurrentSong ? <>{ spotifyCurrentSong }</> : <>-</>}
              {" "}
            </span>
          </> : <>
            <span id="currentTrack">
              {" "}
              <a href="api/spotify">Войти</a>{" "}
            </span>
          </>}
        </div>
      </div>
    </div>
  );
}
