import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Obsoverlay.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.container}>
        <div className={styles.title}>
          Последний подписчик: <span id="lastFollower">---</span>
        </div>
        <div className={styles.title}>
          Последний донат: <span id="lastDonation">---</span>
        </div>
        <div className={styles.title}>
          Сейчас играет:{" "}
          <span id="currentTrack">
            {" "}
            <a href="api/spotify">Войти</a>{" "}
          </span>
        </div>
      </div>
    </div>
  );
}
